### ISSUE TITLE
[Question] Recommendation for A/B testing a particular JavaScript snippet with Web Vitals Report?

### ISSUE THREAD

**Issue by justinhelmer** [GoogleChromeLabs/web-vitals-report#1]
Hello,

We are looking to implement Core Web Vitals first on our site, then eventually on our clients' websites. Particularly, we want to measure the web vitals both with and without a particular JavaScript snippet running on the page, and be able to easily compare/contrast these values to understand the UX impact of the snippet.

We can implement a "coin flip" mechanic that determines whether or not to inject the JavaScript, and report on the Core Web Vitals in every case.

It seems like we might somehow be able to take advantage of `eventLabel` and grouping (or maybe some other GA event property), but are unsure how we can configure web-vitals-report correctly for this particular use-case.

Are there any recommendations on how to approach this problem? Any help would be greatly appreciated.

**Comment by philipwalton** [comment]
Yes, this is possible with the Web Vitals Report. It can be done using a [custom dimension](https://support.google.com/analytics/answer/2709828?hl=en) to set your variant, and then either [custom segments](https://support.google.com/analytics/answer/3124493?hl=en) or [report filters](https://github.com/GoogleChromeLabs/web-vitals-report#advanced-configuration-options) in the Web Vitals Report interface.

> We can implement a "coin flip" mechanic that determines whether or not to inject the JavaScript, and report on the Core Web Vitals in every case.

If you can ensure that all page loads from the same user will end up in the same variant, then I'd recommend the approach that uses custom segments. If you can't ensure that, then I'd recommend creating two reports and using report filters.

Regardless of which strategy you pick, the first step is the same:

### 1. Update your tracking code to set the variant as a custom dimension

Assuming your [custom dimension](https://support.google.com/analytics/answer/2709828?hl=en) is the first one you've created (e.g. `dimension1`), then you'd update your code that [sends your Web Vitals data to Google Analytics](https://github.com/GoogleChrome/web-vitals#send-the-results-to-google-analytics) to something like this (notice the addition of the `dimension1` entry in the object:

```diff
import {getCLS, getFID, getLCP} from 'web-vitals';

function sendToGoogleAnalytics({name, delta, id}) {
  // Assumes the global `ga()` function exists, see:
  // https://developers.google.com/analytics/devguides/collection/analyticsjs
  ga('send', 'event', {
    eventCategory: 'Web Vitals',
    eventAction: name,
    // The `id` value will be unique to the current page load. When sending
    // multiple values from the same page (e.g. for CLS), Google Analytics can
    // compute a total by grouping on this ID (note: requires `eventLabel` to
    // be a dimension in your report).
    eventLabel: id,
    // Google Analytics metrics must be integers, so the value is rounded.
    // For CLS the value is first multiplied by 1000 for greater precision
    // (note: increase the multiplier for greater precision if needed).
    eventValue: Math.round(name === 'CLS' ? delta * 1000 : delta),
    // Use a non-interaction event to avoid affecting bounce rate.
    nonInteraction: true,
+   dimension1: 'A', // or 'B' (or on/off, true/false, etc.)
    // Use `sendBeacon()` if the browser supports it.
    transport: 'beacon',
  });
}

getCLS(sendToGoogleAnalytics);
getFID(sendToGoogleAnalytics);
getLCP(sendToGoogleAnalytics);
```

Alternatively you can set this dimension on the tracker object itself so it gets sent with all beacons.

```diff
ga('create', 'UA-XXXXX-Y', 'auto');
+ ga('set', 'dimension1', 'A'); // or 'B' (or on/off, true/false, etc.)
ga('send', 'pageview');
```

Once that data is being sent, the next step would be to create a report to show the different variants. As I mentioned above, you can do this by either:

a) Creating a report that compares two [custom segments](https://support.google.com/analytics/answer/3124493?hl=en), or
b) Creating two reports (for whatever segments you want) and use [report filters](https://github.com/GoogleChromeLabs/web-vitals-report#advanced-configuration-options) to isolate the variants.

### 2a) Create a report that compares two custom segments

Create two [custom segments](https://support.google.com/analytics/answer/3124493?hl=en) based on the value of your custom dimension:

1) Sessions that contain an event where the event category is "Web Vitals" and the `dimenions1` value is "A".
2) Sessions that contain an event where the event category is "Web Vitals" and the `dimenions1` value is "B".

<img width="895" alt="Screen Shot 2021-01-13 at 5 01 38 PM" src="https://user-images.githubusercontent.com/326742/104530540-08d29680-55c1-11eb-8f56-8f213f42d9e9.png">

Then you could create a single report on the Web Vitals Report site comparing these two segments.

Note: If you set the custom dimension on the tracker object so it gets sent with all beacons, then you can make your segments slightly more accurate by indicating that the **first** interaction in the segment should contain the dimension variant, like so:

<img width="894" alt="Screen Shot 2021-01-13 at 5 00 46 PM" src="https://user-images.githubusercontent.com/326742/104530559-10923b00-55c1-11eb-9709-4a0e66220f1d.png">

### 2b) Create two reports using report filters

The other reporting option is to use filters instead of segments. The Web Vitals Report is built around the premise of comparing two segments in a single report, but you could also compare your A/B variants across two separate reports with different filter settings.

For the first report, set the filter settings to something like this:

```
ga:eventCategory==Web Vitals;ga:dimension1==A
```

Then run a second report and update the filters to this:

```
ga:eventCategory==Web Vitals;ga:dimension1==B
```

If you do this in two separate tabs you should be able to easily switch back and forth to compare the results.

I hope that helps!

**Comment by justinhelmer** [comment]
@philipwalton - Wow, this is incredibly useful. I hope other stumble upon this as well, as it is invaluable information.

Thanks to your help in [getting the UMD+polyfill reporting working](https://github.com/GoogleChrome/web-vitals/issues/116) (currently working in Chrome), we can start to capture values and set up `web-vitals-report`, at which point I will be able to come back and fully digest this.

**Comment by justinhelmer** [comment]
@philipwalton - I had time this evening to set up everything according to how you have articulated it here. I went with (2a) and setting up custom segments.

I am seeing the events showing up in the analytics dashboard, however the `web-vitals-report` configuration form doesn't seem to like it.

Does this trigger any ideas for you? I feel like we are SO CLOSE!

```js
function sendToGoogleAnalytics({name, delta, id}) {
  console.log('sending web vitals event', name, delta, id);
  ga("send", "event", {
    eventCategory: 'Web Vitals',
    eventAction: name,
    // The `id` value will be unique to the current page load. When sending
    // multiple values from the same page (e.g. for CLS), Google Analytics can
    // compute a total by grouping on this ID (note: requires `eventLabel` to
    // be a dimension in your report).
    eventLabel: id,
    // Google Analytics metrics must be integers, so the value is rounded.
    // For CLS the value is first multiplied by 1000 for greater precision
    // (note: increase the multiplier for greater precision if needed).
    eventValue: Math.round(name === 'CLS' ? delta * 1000 : delta),
    // Use a non-interaction event to avoid affecting bounce rate.
    nonInteraction: true,
    dimension16: 'yes', // Intellimize Script Included
    // Use `sendBeacon()` if the browser supports it.
    transport: 'beacon',
  });
}
```

![Screen Shot 2021-01-14 at 6 57 21 PM](https://user-images.githubusercontent.com/1403438/104675419-566f0200-569a-11eb-9abd-1f79332fe3d3.png)

![Screen Shot 2021-01-14 at 6 57 45 PM](https://user-images.githubusercontent.com/1403438/104675452-64bd1e00-569a-11eb-9f4e-920ba3452555.png)

![Screen Shot 2021-01-14 at 6 58 18 PM](https://user-images.githubusercontent.com/1403438/104675487-77cfee00-569a-11eb-8787-8f1311183a07.png)

![Screen Shot 2021-01-14 at 6 58 36 PM](https://user-images.githubusercontent.com/1403438/104675504-828a8300-569a-11eb-820f-9ceec52b7752.png)

<img width="688" alt="Screen Shot 2021-01-14 at 7 01 17 PM" src="https://user-images.githubusercontent.com/1403438/104675735-ead96480-569a-11eb-968e-c3271ba6055c.png">

<img width="1447" alt="Screen Shot 2021-01-14 at 7 01 41 PM" src="https://user-images.githubusercontent.com/1403438/104675776-fb89da80-569a-11eb-975b-0101edf68263.png">

**Comment by philipwalton** [comment]
Try using a custom date range. If I recall correctly, "Last 7 days" does not include the current day.

**Comment by justinhelmer** [comment]
Bingo :-)
