### ISSUE TITLE
TTFB

### ISSUE THREAD

**Issue by JFM74** [GoogleChromeLabs/web-vitals-report#2]
Hi,
I'm sending TTFB to Analytics - as per https://github.com/GoogleChrome/web-vitals/#send-the-results-to-google-analytics

But there doesn't seem to be a way of reporting on this?

A workaround seems to be to change the name of another metric to TTFB - but is there a better way?

Thanks

**Comment by philipwalton** [comment]
One of the intentions behind the Web Vitals Report is that people would fork it and customize it to their needs. My recommendation for folks who want to track FCP and TTFB is that they do just that.

Alternatively, there are a lot of RUM analytics providers who also measure and provide very detailed reports on a variety of performance metrics (including TTFB).

The goal of the Web Vitals Report is not that it competes with RUM analytics tools. The goal is to help developers understand how they can build their own tools.

> A workaround seems to be to change the name of another metric to TTFB - but is there a better way?

That's not a great workaround since one of the main features of the Web Vitals Report is color-coding each metric value result by what rating it gets (e.g. green = "good", yellow = "needs improvement", red = "poor"). If you sent TTFB data instead of FID (for example), then everything would probably show red.
