### ISSUE TITLE
GA v4 web property support ?

### ISSUE THREAD

**Issue by centminmod** [GoogleChromeLabs/web-vitals-report#4]
It seems the Web Vitals Report doesn't support GA v4 analytics as signing into my GA account from https://web-vitals-report.web.app/, only legacy/universal web properties are listed. Any GA v4 analytic web properties do not show up in the listing to select?

whoops just read https://github.com/GoogleChromeLabs/web-vitals-report#google-analytics-4-ga4-properties-are-not-supported !

**Comment by philipwalton** [comment]
That's right, this tool does not support GA4 because the GA4 APIs needed are not yet available. However, we're presenting some content at Google I/O on this topic that might be helpful to you if you're already using GA4: https://events.google.com/io/session/0deaa89f-f331-48ae-a8d7-e2f0aedddf82?lng=en

**Comment by Mistic92** [comment]
Looks like GA4 should be available by api https://developers.google.com/analytics/devguides/reporting/data/v1 but maybe I'm looking at wrong place

**Comment by philipwalton** [comment]
The API is still in beta, and there are a few key features that make it not possible to implement yet. However, for GA4, I honestly recommend the approach outlined here: https://web.dev/vitals-ga4/
