### ISSUE TITLE
CLS graph shows excessively high count of 0 values

### ISSUE THREAD

**Issue by Lucent** [GoogleChromeLabs/web-vitals-report#6]
Scores for p75 for CLS seem to be computed correctly, but display a graph with an extremely large number of 0 values. Are null values showing up on the graph as 0 but properly discarded in the average computation?

The following image shows mobile traffic CLS which the dashboard scores reasonably as 0.135 despite the graph showing almost entirely 0 values that would imply an average way lower, possibly 0.02. 
![image](https://user-images.githubusercontent.com/106736/118737262-4f4b3280-b7f9-11eb-8234-5148bf121581.png)

Other graphs show distributions concordant with their averages and without an excess of 0 values.

**Comment by philipwalton** [comment]
Sorry for the late response! Not sure how I missed this issue before...

What you're seeing is correct. There are a lot of 0 values because, for many of your visitors, there are no layout shifts, so the CLS value is 0.

The numbers you are seeing at the top of the image are not actually averages, they're 75th-percentile values (which is [what is recommended](https://web.dev/vitals/#:~:text=For%20each%20of%20the%20above%20metrics%2C%20to%20ensure%20you%27re%20hitting%20the%20recommended%20target%20for%20most%20of%20your%20users%2C%20a%20good%20threshold%20to%20measure%20is%20the%2075th%20percentile%20of%20page%20loads%2C%20segmented%20across%20mobile%20and%20desktop%20devices.) for reporting Core Web Vitals metrics).
