### ISSUE TITLE
App at https://web-vitals-report is throwing HTTP 503 error

### ISSUE THREAD

**Issue by whyleyc** [GoogleChromeLabs/web-vitals-report#7]
For the last couple of days, the hosted version of this app at https://web-vitals-report.web.app/ has been throwing an HTTP 503 error when I try to generate a report from a linked Google Analytics account:

![cwv-503](https://user-images.githubusercontent.com/1568556/118975429-ea641980-b96b-11eb-8b16-9fc9762df121.png)

Is the hosted service currently down for maintenance?

**Comment by groseler** [comment]
The app it is really unstable. It is also a shame that it doesn't show the TTFB values.

**Comment by philipwalton** [comment]
This app does not control the Google Analytics API endpoints, so when those are down for particular users, there's nothing that can be done from the app's perspective.

For what it's worth, I have not experience any downtime myself. Are you using other services that require the Google Analytics APIs? If so, it's possible you're exhausting your quota and that's why you're seeing these errors.

**Comment by tunetheweb** [comment]
Closing this. Feel free to reopen if still experiencing issues.
